// apps/test-vite-vue/src/App.vue
<script setup lang="ts">
import { ref, computed } from "vue";

const count = ref(0);
const theme = ref<"light" | "dark">("light");

const alertTypes = ["info", "success", "warning", "error"] as const;
type AlertType = (typeof alertTypes)[number];

function getAlertClasses(type: AlertType) {
  const classes: Record<AlertType, string> = {
    info: "bg-blue-50 border-blue-200 text-blue-800",
    success: "bg-green-50 border-green-200 text-green-800",
    warning: "bg-yellow-50 border-yellow-200 text-yellow-800",
    error: "bg-red-50 border-red-200 text-red-800",
  };
  return classes[type];
}

const themeClass = computed(() =>
  theme.value === "light" ? "bg-gray-100" : "bg-gray-900"
);

function toggleTheme() {
  theme.value = theme.value === "light" ? "dark" : "light";
}
</script>

<template>
  <div :class="['min-h-screen transition-colors duration-300', themeClass]">
    <!-- Header -->
    <header class="bg-white shadow-sm">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
        <div class="flex items-center justify-between">
          <h1 class="text-2xl font-bold text-gray-900">
            TailwindCSS Obfuscator - Vue Test
          </h1>
          <button
            class="px-4 py-2 bg-gray-200 text-gray-800 rounded-lg hover:bg-gray-300 transition-colors"
            @click="toggleTheme"
          >
            Toggle Theme
          </button>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <!-- Counter Section -->
      <section class="mb-8">
        <div class="bg-white rounded-xl shadow-lg p-6">
          <h3 class="text-lg font-bold text-gray-900 mb-4">Counter Example</h3>
          <div class="flex items-center gap-4">
            <button
              class="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors"
              @click="count++"
            >
              Increment
            </button>
            <span class="text-xl font-mono text-gray-700">{{ count }}</span>
            <button
              class="px-4 py-2 bg-gray-200 text-gray-800 rounded-lg hover:bg-gray-300 transition-colors"
              @click="count = 0"
            >
              Reset
            </button>
          </div>
        </div>
      </section>

      <!-- Alerts Section -->
      <section class="mb-8 space-y-4">
        <h2 class="text-xl font-semibold text-gray-900">Alerts</h2>
        <div
          v-for="type in alertTypes"
          :key="type"
          :class="['p-4 rounded-lg border', getAlertClasses(type)]"
        >
          This is a {{ type }} alert
        </div>
      </section>

      <!-- Cards Grid -->
      <section class="mb-8">
        <h2 class="text-xl font-semibold text-gray-900 mb-4">Feature Cards</h2>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <div class="bg-white rounded-xl shadow-lg p-6 hover:shadow-xl transition-shadow">
            <h3 class="text-lg font-bold text-gray-900 mb-2">Vue 3</h3>
            <p class="text-gray-600">Full support for Vue 3 Composition API</p>
            <div class="mt-4 flex gap-2">
              <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
                Composition API
              </span>
            </div>
          </div>
          <div class="bg-white rounded-xl shadow-lg p-6 hover:shadow-xl transition-shadow">
            <h3 class="text-lg font-bold text-gray-900 mb-2">SFC Support</h3>
            <p class="text-gray-600">Single File Components with scoped styles</p>
            <div class="mt-4 flex gap-2">
              <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                .vue files
              </span>
            </div>
          </div>
          <div class="bg-white rounded-xl shadow-lg p-6 hover:shadow-xl transition-shadow">
            <h3 class="text-lg font-bold text-gray-900 mb-2">TypeScript</h3>
            <p class="text-gray-600">First-class TypeScript support</p>
            <div class="mt-4 flex gap-2">
              <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-purple-100 text-purple-800">
                Type Safe
              </span>
            </div>
          </div>
        </div>
      </section>

      <!-- Dynamic Classes with v-bind -->
      <section class="mb-8">
        <h2 class="text-xl font-semibold text-gray-900 mb-4">Dynamic Binding</h2>
        <div class="space-y-4">
          <div
            v-for="n in 5"
            :key="n"
            :class="[
              'p-4 rounded-lg',
              n % 2 === 0 ? 'bg-blue-100' : 'bg-green-100',
              `opacity-${20 * n}`,
            ]"
          >
            Item {{ n }} with dynamic opacity
          </div>
        </div>
      </section>

      <!-- Excluded class -->
      <section class="mb-8">
        <h2 class="text-xl font-semibold text-gray-900 mb-4">Excluded Classes</h2>
        <div class="no-obfuscate p-4 bg-yellow-100 rounded">
          This div has "no-obfuscate" class which should be excluded
        </div>
      </section>
    </main>

    <!-- Footer -->
    <footer class="bg-gray-800 text-white py-8">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
        <p class="text-gray-400">TailwindCSS Obfuscator - Vite + Vue Test App</p>
      </div>
    </footer>
  </div>
</template>

// apps/test-nextjs/src/app/page.tsx
"use client";

import { useState } from "react";
import clsx from "clsx";

// Button component
function Button({
  variant = "primary",
  children,
  onClick,
}: {
  variant?: "primary" | "secondary";
  children: React.ReactNode;
  onClick?: () => void;
}) {
  return (
    <button
      onClick={onClick}
      className={clsx(
        "rounded-lg px-4 py-2 font-semibold transition-colors",
        variant === "primary" && "bg-blue-500 text-white hover:bg-blue-600",
        variant === "secondary" && "bg-gray-200 text-gray-800 hover:bg-gray-300"
      )}
    >
      {children}
    </button>
  );
}

// Card component
function Card({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-xl bg-white p-6 shadow-lg transition-shadow hover:shadow-xl">
      <h3 className="mb-4 text-lg font-bold text-gray-900">{title}</h3>
      {children}
    </div>
  );
}

export default function Home() {
  const [count, setCount] = useState(0);

  return (
    <div className="min-h-screen">
      {/* Header */}
      <header className="bg-white shadow-sm">
        <div className="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8">
          <h1 className="text-2xl font-bold text-gray-900">
            TailwindCSS Obfuscator - Next.js Test
          </h1>
        </div>
      </header>

      {/* Main */}
      <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
        {/* Counter */}
        <section className="mb-8">
          <Card title="Counter Example">
            <div className="flex items-center gap-4">
              <Button variant="primary" onClick={() => setCount((c) => c + 1)}>
                Increment
              </Button>
              <span className="font-mono text-xl text-gray-700">{count}</span>
              <Button variant="secondary" onClick={() => setCount(0)}>
                Reset
              </Button>
            </div>
          </Card>
        </section>

        {/* Cards Grid */}
        <section className="mb-8">
          <h2 className="mb-4 text-xl font-semibold text-gray-900">Feature Cards</h2>
          <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
            <Card title="Next.js App Router">
              <p className="text-gray-600">Full support for Next.js 13+ App Router</p>
              <div className="mt-4">
                <span className="inline-flex items-center rounded-full bg-green-100 px-2.5 py-0.5 text-xs font-medium text-green-800">
                  Server Components
                </span>
              </div>
            </Card>
            <Card title="Webpack Integration">
              <p className="text-gray-600">Uses Webpack plugin for class obfuscation</p>
              <div className="mt-4">
                <span className="inline-flex items-center rounded-full bg-blue-100 px-2.5 py-0.5 text-xs font-medium text-blue-800">
                  Production Only
                </span>
              </div>
            </Card>
            <Card title="TypeScript">
              <p className="text-gray-600">Full TypeScript support</p>
              <div className="mt-4">
                <span className="inline-flex items-center rounded-full bg-purple-100 px-2.5 py-0.5 text-xs font-medium text-purple-800">
                  Type Safe
                </span>
              </div>
            </Card>
          </div>
        </section>

        {/* Responsive Test */}
        <section className="mb-8">
          <h2 className="mb-4 text-xl font-semibold text-gray-900">Responsive Design</h2>
          <div className="rounded-lg bg-white p-4 shadow">
            <p className="text-sm sm:text-base md:text-lg lg:text-xl xl:text-2xl">
              This text changes size at different breakpoints
            </p>
          </div>
        </section>

        {/* Excluded Class */}
        <section className="mb-8">
          <h2 className="mb-4 text-xl font-semibold text-gray-900">Excluded Classes</h2>
          <div className="no-obfuscate rounded bg-yellow-100 p-4">
            This div has the no-obfuscate class which should be excluded
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="bg-gray-800 py-8 text-white">
        <div className="mx-auto max-w-7xl px-4 text-center sm:px-6 lg:px-8">
          <p className="text-gray-400">TailwindCSS Obfuscator - Next.js Test App</p>
        </div>
      </footer>
    </div>
  );
}
