// apps/test-qwik/src/routes/index.tsx
import { component$, useSignal } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";

const FeatureCard = component$((props: { title: string; icon: string; description: string }) => {
  return (
    <div class="rounded-lg bg-white p-6 shadow-md transition-shadow hover:shadow-lg">
      <div class="bg-qwik-100 mb-4 flex h-12 w-12 items-center justify-center rounded-lg">
        <span class="text-2xl">{props.icon}</span>
      </div>
      <h3 class="mb-2 text-lg font-semibold text-gray-800">{props.title}</h3>
      <p class="text-sm text-gray-600">{props.description}</p>
    </div>
  );
});

export default component$(() => {
  const count = useSignal(0);

  const features = [
    {
      title: "Resumability",
      icon: "⏯️",
      description: "No hydration needed - Qwik resumes where the server left off.",
    },
    {
      title: "Lazy Loading",
      icon: "🦥",
      description: "Only loads JavaScript when interactions require it.",
    },
    {
      title: "O(1) Startup",
      icon: "🚀",
      description: "Constant time to interactive, regardless of app complexity.",
    },
    {
      title: "Familiar JSX",
      icon: "💡",
      description: "React-like syntax with signals for reactivity.",
    },
    {
      title: "Tailwind v4",
      icon: "🎨",
      description: "Modern CSS-first styling with Tailwind CSS v4.",
    },
    {
      title: "Obfuscated",
      icon: "🔒",
      description: "Class names obfuscated for production security.",
    },
  ];

  return (
    <main class="from-qwik-100 to-primary-100 min-h-screen bg-gradient-to-br px-4 py-12">
      <div class="mx-auto max-w-5xl">
        {/* Header */}
        <header class="mb-12 text-center">
          <h1 class="mb-4 text-4xl font-extrabold text-gray-900 md:text-5xl">
            Qwik + Tailwind CSS v4
          </h1>
          <p class="mx-auto max-w-2xl text-lg text-gray-600">
            Instant-on web apps with resumability. Testing tailwindcss-obfuscator integration.
          </p>
        </header>

        {/* Counter */}
        <div class="mb-12 rounded-xl bg-white p-8 text-center shadow-lg">
          <h2 class="mb-6 text-2xl font-bold text-gray-800">Resumable Counter</h2>
          <div class="flex items-center justify-center gap-6">
            <button
              onClick$={() => count.value--}
              class="h-14 w-14 rounded-full bg-red-500 text-2xl font-bold text-white shadow-md transition-colors hover:bg-red-600"
            >
              -
            </button>
            <span class="text-qwik-600 min-w-[100px] text-5xl font-bold">{count.value}</span>
            <button
              onClick$={() => count.value++}
              class="h-14 w-14 rounded-full bg-green-500 text-2xl font-bold text-white shadow-md transition-colors hover:bg-green-600"
            >
              +
            </button>
          </div>
        </div>

        {/* Features Grid */}
        <div class="mb-12 grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
          {features.map((feature) => (
            <FeatureCard
              key={feature.title}
              title={feature.title}
              icon={feature.icon}
              description={feature.description}
            />
          ))}
        </div>

        {/* CTA Buttons */}
        <div class="flex flex-wrap justify-center gap-4">
          <button class="bg-qwik-600 hover:bg-qwik-500 rounded-lg px-8 py-4 font-semibold text-white shadow-lg transition-colors">
            Get Started
          </button>
          <button class="bg-primary-600 hover:bg-primary-700 rounded-lg px-8 py-4 font-semibold text-white shadow-lg transition-colors">
            Documentation
          </button>
          <button class="rounded-lg border-2 border-gray-300 px-8 py-4 font-semibold text-gray-700 transition-colors hover:border-gray-400 hover:bg-gray-50">
            View Source
          </button>
        </div>
      </div>
    </main>
  );
});

export const head: DocumentHead = {
  title: "Qwik + Tailwind CSS v4",
  meta: [
    {
      name: "description",
      content: "Testing tailwindcss-obfuscator with Qwik",
    },
  ],
};

// apps/test-sveltekit/src/routes/+page.svelte
<script lang="ts">
  let count = $state(0);

  function increment() {
    count++;
  }

  function decrement() {
    count--;
  }
</script>

<svelte:head>
  <title>SvelteKit + Tailwind CSS v4</title>
  <meta name="description" content="tailwindcss-obfuscator end-to-end test on SvelteKit." />
</svelte:head>

<div class="min-h-screen bg-gradient-to-br from-primary-50 to-secondary-100 py-12 px-4">
  <div class="max-w-4xl mx-auto">
    <!-- Header -->
    <header class="text-center mb-12">
      <h1 class="text-4xl font-bold text-gray-900 mb-4">
        SvelteKit + Tailwind CSS v4
      </h1>
      <p class="text-lg text-gray-600">
        Testing tailwindcss-obfuscator with SvelteKit
      </p>
    </header>

    <!-- Counter Card -->
    <div class="bg-white rounded-xl shadow-lg p-8 mb-8">
      <h2 class="text-2xl font-semibold text-gray-800 mb-6 text-center">
        Interactive Counter
      </h2>

      <div class="flex items-center justify-center gap-6">
        <button
          onclick={decrement}
          class="w-12 h-12 rounded-full bg-red-500 text-white font-bold text-2xl hover:bg-red-600 transition-colors flex items-center justify-center"
        >
          -
        </button>

        <span class="text-5xl font-bold text-gray-800 min-w-[80px] text-center">
          {count}
        </span>

        <button
          onclick={increment}
          class="w-12 h-12 rounded-full bg-green-500 text-white font-bold text-2xl hover:bg-green-600 transition-colors flex items-center justify-center"
        >
          +
        </button>
      </div>
    </div>

    <!-- Features Grid -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
      <div class="bg-white rounded-lg shadow-md p-6 hover:shadow-lg transition-shadow">
        <div class="w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center mb-4">
          <span class="text-2xl">⚡</span>
        </div>
        <h3 class="text-lg font-semibold text-gray-800 mb-2">Fast</h3>
        <p class="text-gray-600 text-sm">
          SvelteKit compiles to minimal JavaScript for blazing performance.
        </p>
      </div>

      <div class="bg-white rounded-lg shadow-md p-6 hover:shadow-lg transition-shadow">
        <div class="w-12 h-12 bg-secondary-100 rounded-lg flex items-center justify-center mb-4">
          <span class="text-2xl">🎨</span>
        </div>
        <h3 class="text-lg font-semibold text-gray-800 mb-2">Stylish</h3>
        <p class="text-gray-600 text-sm">
          Tailwind CSS v4 with CSS-first configuration.
        </p>
      </div>

      <div class="bg-white rounded-lg shadow-md p-6 hover:shadow-lg transition-shadow">
        <div class="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mb-4">
          <span class="text-2xl">🔒</span>
        </div>
        <h3 class="text-lg font-semibold text-gray-800 mb-2">Obfuscated</h3>
        <p class="text-gray-600 text-sm">
          Class names are obfuscated for production builds.
        </p>
      </div>
    </div>

    <!-- Buttons -->
    <div class="flex flex-wrap justify-center gap-4">
      <button class="px-6 py-3 bg-primary-600 text-white rounded-lg font-medium hover:bg-primary-700 transition-colors">
        Primary Button
      </button>
      <button class="px-6 py-3 bg-secondary-600 text-white rounded-lg font-medium hover:bg-secondary-500 transition-colors">
        Secondary Button
      </button>
      <button class="px-6 py-3 border-2 border-gray-300 text-gray-700 rounded-lg font-medium hover:border-gray-400 transition-colors">
        Outline Button
      </button>
    </div>
  </div>
</div>
